apiVersion: v1
kind: Service
metadata:
   labels:
      app: nginx
   name: my-node-port-svc
   namespace: demo
spec:
   type: NodePort
   selector:
      app: nginx 
   ports:
   - port: 80
     targetPort: 80
     nodePort: 30008
     protocol: TCP
